"""
helpers.py - Utility helpers for text processing, domain parsing, and exports.
"""

from datetime import datetime, timezone
import json
import re
from typing import Any, Dict, List, Optional
from urllib.parse import urlparse


def extract_domain(url: str) -> str:
    """Extracts a clean, human-readable domain name from a URL."""
    if not url:
        return "Unknown Source"
    try:
        parsed = urlparse(url)
        domain = parsed.netloc or parsed.path
        # Strip common subdomains and ports
        domain = re.sub(r"^www\.", "", domain, flags=re.IGNORECASE)
        domain = domain.split(":")[0]
        return domain if domain else "web-source"
    except Exception:
        return "web-source"


def clean_text(text: Optional[str]) -> str:
    """Sanitizes raw text, collapses whitespace, and strips control characters."""
    if not text:
        return ""
    # Remove null bytes and non-printable control characters
    cleaned = "".join(ch for ch in text if ch.isprintable() or ch in "\n\r\t ")
    # Normalize multiple newlines and spaces line-by-line
    lines = [re.sub(r"[ \t]+", " ", line).strip() for line in cleaned.splitlines()]
    # Remove excessive blank lines
    collapsed: List[str] = []
    blank_count = 0
    for line in lines:
        if not line:
            blank_count += 1
            if blank_count <= 1:
                collapsed.append("")
        else:
            blank_count = 0
            collapsed.append(line)

    return "\n".join(collapsed).strip()


def truncate_text(text: str, max_chars: int = 300, suffix: str = "...") -> str:
    """Truncates text neatly at word boundaries."""
    if not text or len(text) <= max_chars:
        return text or ""
    truncated = text[:max_chars].rsplit(" ", 1)[0]
    return f"{truncated}{suffix}"


def build_markdown_report_export(
    question: str,
    report_content: str,
    sources: List[Dict[str, Any]],
    generated_at: Optional[str] = None,
) -> str:
    """
    Constructs a standalone Markdown document suitable for export, sharing, or archiving.
    """
    timestamp = generated_at or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    
    header = f"""# ResearchAI Report: {question}

> **Generated by ResearchAI** | Autonomous Multi-Source Research Engine  
> **Date:** {timestamp}  
> **Total Sourced References:** {len(sources)}

---

"""
    body = report_content.strip()
    
    sources_section = "\n\n## Verified Sources & References\n\n"
    if sources:
        for idx, src in enumerate(sources, 1):
            title = src.get("title", "Untitled Source")
            url = src.get("url", "#")
            domain = src.get("domain") or extract_domain(url)
            summary = src.get("summary") or src.get("snippet") or "No excerpt available."
            sources_section += f"**[{idx}] [{title}]({url})**  \n"
            sources_section += f"- **Domain:** `{domain}`  \n"
            sources_section += f"- **Key Evidence / Excerpt:** {truncate_text(summary, 220)}  \n\n"
    else:
        sources_section += "_No external web sources were collected for this session._\n"

    footer = "\n---\n*Report compiled autonomously by ResearchAI. All cited facts reflect retrieved evidence.*"
    
    return header + body + sources_section + footer


def build_json_export(
    question: str,
    plan: Dict[str, Any],
    report: str,
    sources: List[Dict[str, Any]],
    contradictions: List[Dict[str, Any]],
    metrics: Dict[str, Any],
) -> str:
    """Serializes the entire research session state to formatted JSON."""
    payload = {
        "metadata": {
            "application": "ResearchAI",
            "version": "1.0.0",
            "timestamp": datetime.now(timezone.utc).isoformat(),
        },
        "query": question,
        "plan": plan,
        "metrics": metrics,
        "report_markdown": report,
        "contradictions_or_divergences": contradictions,
        "sources": sources,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False)
